public class AccentureRunner{
public static void main(String[] args){
Accenture accenture = new Accenture();
System.out.println("EMPLOYE NAME :"+accenture.employe_name);
System.out.println("EMPLOYE AGE :"+accenture.age);
System.out.println("EMPLOYE ID NUMBER :"+accenture.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+accenture.experience);
System.out.println("EMPLOYE SALARY :"+accenture.salary);
System.out.println("EMPLOYE STATUS :"+accenture.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture.gender);
System.out.println("EMPLOYE LOCATION :"+accenture.location);
System.out.println("EMPLOYE JOIN DATE :"+accenture.joining_date);
System.out.println("EMPLOYE NAME :"+accenture.employe_name1);
System.out.println("EMPLOYE AGE :"+accenture.age1);
System.out.println("EMPLOYE ID NUMBER :"+accenture.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+accenture.experience1);
System.out.println("EMPLOYE SALARY :"+accenture.salary1);
System.out.println("EMPLOYE STATUS :"+accenture.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture.gender1);
System.out.println("EMPLOYE LOCATION :"+accenture.location1);
System.out.println("EMPLOYE JOIN DATE :"+accenture.joining_date1);

Accenture accenture1 = new Accenture();
System.out.println("EMPLOYE NAME :"+accenture1.employe_name);
System.out.println("EMPLOYE AGE :"+accenture1.age);
System.out.println("EMPLOYE ID NUMBER :"+accenture1.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture1.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture1.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+accenture1.experience);
System.out.println("EMPLOYE SALARY :"+accenture1.salary);
System.out.println("EMPLOYE STATUS :"+accenture1.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture1.gender);
System.out.println("EMPLOYE LOCATION :"+accenture1.location);
System.out.println("EMPLOYE JOIN DATE :"+accenture1.joining_date);
System.out.println("EMPLOYE NAME :"+accenture1.employe_name1);
System.out.println("EMPLOYE AGE :"+accenture1.age1);
System.out.println("EMPLOYE ID NUMBER :"+accenture1.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture1.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture1.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+accenture1.experience1);
System.out.println("EMPLOYE SALARY :"+accenture1.salary1);
System.out.println("EMPLOYE STATUS :"+accenture1.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture1.gender1);
System.out.println("EMPLOYE LOCATION :"+accenture1.location1);
System.out.println("EMPLOYE JOIN DATE :"+accenture1.joining_date1);

Accenture accenture2 = new Accenture();
System.out.println("EMPLOYE NAME :"+accenture2.employe_name);
System.out.println("EMPLOYE AGE :"+accenture2.age);
System.out.println("EMPLOYE ID NUMBER :"+accenture2.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture2.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture2.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+accenture2.experience);
System.out.println("EMPLOYE SALARY :"+accenture2.salary);
System.out.println("EMPLOYE STATUS :"+accenture2.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture2.gender);
System.out.println("EMPLOYE LOCATION :"+accenture2.location);
System.out.println("EMPLOYE JOIN DATE :"+accenture2.joining_date);
System.out.println("EMPLOYE NAME :"+accenture2.employe_name1);
System.out.println("EMPLOYE AGE :"+accenture2.age1);
System.out.println("EMPLOYE ID NUMBER :"+accenture2.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture2.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture2.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+accenture2.experience1);
System.out.println("EMPLOYE SALARY :"+accenture2.salary1);
System.out.println("EMPLOYE STATUS :"+accenture2.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture2.gender1);
System.out.println("EMPLOYE LOCATION :"+accenture2.location1);
System.out.println("EMPLOYE JOIN DATE :"+accenture2.joining_date1);

Accenture accenture3 = new Accenture();
System.out.println("EMPLOYE NAME :"+accenture3.employe_name);
System.out.println("EMPLOYE AGE :"+accenture3.age);
System.out.println("EMPLOYE ID NUMBER :"+accenture3.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture3.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture3.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+accenture3.experience);
System.out.println("EMPLOYE SALARY :"+accenture3.salary);
System.out.println("EMPLOYE STATUS :"+accenture3.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture3.gender);
System.out.println("EMPLOYE LOCATION :"+accenture3.location);
System.out.println("EMPLOYE JOIN DATE :"+accenture3.joining_date);
System.out.println("EMPLOYE NAME :"+accenture3.employe_name1);
System.out.println("EMPLOYE AGE :"+accenture3.age1);
System.out.println("EMPLOYE ID NUMBER :"+accenture3.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+accenture3.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+accenture3.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+accenture3.experience1);
System.out.println("EMPLOYE SALARY :"+accenture3.salary1);
System.out.println("EMPLOYE STATUS :"+accenture3.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+accenture3.gender1);
System.out.println("EMPLOYE LOCATION :"+accenture3.location1);
System.out.println("EMPLOYE JOIN DATE :"+accenture3.joining_date1);

new Accenture();
}
}
