public class CentomRunner{
public static void main(String[] args){
Centom centom = new Centom();
System.out.println("EMPLOYE NAME :"+centom.employe_name);
System.out.println("EMPLOYE AGE :"+centom.age);
System.out.println("EMPLOYE ID NUMBER :"+centom.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+centom.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+centom.experience);
System.out.println("EMPLOYE SALARY :"+centom.salary);
System.out.println("EMPLOYE STATUS :"+centom.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom.gender);
System.out.println("EMPLOYE LOCATION :"+centom.location);
System.out.println("EMPLOYE JOIN DATE :"+centom.joining_date);
System.out.println("EMPLOYE NAME :"+centom.employe_name1);
System.out.println("EMPLOYE AGE :"+centom.age1);
System.out.println("EMPLOYE ID NUMBER :"+centom.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+centom.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+centom.experience1);
System.out.println("EMPLOYE SALARY :"+centom.salary1);
System.out.println("EMPLOYE STATUS :"+centom.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom.gender1);
System.out.println("EMPLOYE LOCATION :"+centom.location1);
System.out.println("EMPLOYE JOIN DATE :"+centom.joining_date1);

Centom centom1 = new Centom();
System.out.println("EMPLOYE NAME :"+centom1.employe_name);
System.out.println("EMPLOYE AGE :"+centom1.age);
System.out.println("EMPLOYE ID NUMBER :"+centom1.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom1.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+centom1.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+centom1.experience);
System.out.println("EMPLOYE SALARY :"+centom1.salary);
System.out.println("EMPLOYE STATUS :"+centom1.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom1.gender);
System.out.println("EMPLOYE LOCATION :"+centom1.location);
System.out.println("EMPLOYE JOIN DATE :"+centom1.joining_date);
System.out.println("EMPLOYE NAME :"+centom1.employe_name1);
System.out.println("EMPLOYE AGE :"+centom1.age1);
System.out.println("EMPLOYE ID NUMBER :"+centom1.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom1.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+centom1.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+centom1.experience1);
System.out.println("EMPLOYE SALARY :"+centom1.salary1);
System.out.println("EMPLOYE STATUS :"+centom1.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom1.gender1);
System.out.println("EMPLOYE LOCATION :"+centom1.location1);
System.out.println("EMPLOYE JOIN DATE :"+centom1.joining_date1);

Centom centom2 = new Centom();
System.out.println("EMPLOYE NAME :"+centom2.employe_name);
System.out.println("EMPLOYE AGE :"+centom2.age);
System.out.println("EMPLOYE ID NUMBER :"+centom2.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom2.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+centom2.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+centom2.experience);
System.out.println("EMPLOYE SALARY :"+centom2.salary);
System.out.println("EMPLOYE STATUS :"+centom2.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom2.gender);
System.out.println("EMPLOYE LOCATION :"+centom2.location);
System.out.println("EMPLOYE JOIN DATE :"+centom2.joining_date);
System.out.println("EMPLOYE NAME :"+centom2.employe_name1);
System.out.println("EMPLOYE AGE :"+centom2.age1);
System.out.println("EMPLOYE ID NUMBER :"+centom2.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom2.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+centom2.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+centom2.experience1);
System.out.println("EMPLOYE SALARY :"+centom2.salary1);
System.out.println("EMPLOYE STATUS :"+centom2.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom2.gender1);
System.out.println("EMPLOYE LOCATION :"+centom2.location1);
System.out.println("EMPLOYE JOIN DATE :"+centom2.joining_date1);

Centom centom3 = new Centom();
System.out.println("EMPLOYE NAME :"+centom3.employe_name);
System.out.println("EMPLOYE AGE :"+centom3.age);
System.out.println("EMPLOYE ID NUMBER :"+centom3.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom3.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+centom3.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+centom3.experience);
System.out.println("EMPLOYE SALARY :"+centom3.salary);
System.out.println("EMPLOYE STATUS :"+centom3.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom3.gender);
System.out.println("EMPLOYE LOCATION :"+centom3.location);
System.out.println("EMPLOYE JOIN DATE :"+centom3.joining_date);
System.out.println("EMPLOYE NAME :"+centom3.employe_name1);
System.out.println("EMPLOYE AGE :"+centom3.age1);
System.out.println("EMPLOYE ID NUMBER :"+centom3.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+centom3.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+centom3.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+centom3.experience1);
System.out.println("EMPLOYE SALARY :"+centom3.salary1);
System.out.println("EMPLOYE STATUS :"+centom3.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+centom3.gender1);
System.out.println("EMPLOYE LOCATION :"+centom3.location1);
System.out.println("EMPLOYE JOIN DATE :"+centom3.joining_date1);

new Centom();
}
}