public class MicroSoftRunner{
public static void main(String[] args){
MicroSoft microSoft = new MicroSoft();
System.out.println("EMPLOYE NAME :"+microSoft.employe_name);
System.out.println("EMPLOYE AGE :"+microSoft.age);
System.out.println("EMPLOYE ID NUMBER :"+microSoft.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft.experience);
System.out.println("EMPLOYE SALARY :"+microSoft.salary);
System.out.println("EMPLOYE STATUS :"+microSoft.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft.gender);
System.out.println("EMPLOYE LOCATION :"+microSoft.location);
System.out.println("EMPLOYE JOIN DATE :"+microSoft.joining_date);
System.out.println("EMPLOYE NAME :"+microSoft.employe_name1);
System.out.println("EMPLOYE AGE :"+microSoft.age1);
System.out.println("EMPLOYE ID NUMBER :"+microSoft.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft.experience1);
System.out.println("EMPLOYE SALARY :"+microSoft.salary1);
System.out.println("EMPLOYE STATUS :"+microSoft.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft.gender1);
System.out.println("EMPLOYE LOCATION :"+microSoft.location1);
System.out.println("EMPLOYE JOIN DATE :"+microSoft.joining_date1);

MicroSoft microSoft1 = new MicroSoft();
System.out.println("EMPLOYE NAME :"+microSoft1.employe_name);
System.out.println("EMPLOYE AGE :"+microSoft1.age);
System.out.println("EMPLOYE ID NUMBER :"+microSoft1.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft1.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft1.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft1.experience);
System.out.println("EMPLOYE SALARY :"+microSoft1.salary);
System.out.println("EMPLOYE STATUS :"+microSoft1.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft1.gender);
System.out.println("EMPLOYE LOCATION :"+microSoft1.location);
System.out.println("EMPLOYE JOIN DATE :"+microSoft1.joining_date);
System.out.println("EMPLOYE NAME :"+microSoft1.employe_name1);
System.out.println("EMPLOYE AGE :"+microSoft1.age1);
System.out.println("EMPLOYE ID NUMBER :"+microSoft1.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft1.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft1.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft1.experience1);
System.out.println("EMPLOYE SALARY :"+microSoft1.salary1);
System.out.println("EMPLOYE STATUS :"+microSoft1.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft1.gender1);
System.out.println("EMPLOYE LOCATION :"+microSoft1.location1);
System.out.println("EMPLOYE JOIN DATE :"+microSoft1.joining_date1);

MicroSoft microSoft2 = new MicroSoft();
System.out.println("EMPLOYE NAME :"+microSoft2.employe_name);
System.out.println("EMPLOYE AGE :"+microSoft2.age);
System.out.println("EMPLOYE ID NUMBER :"+microSoft2.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft2.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft2.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft2.experience);
System.out.println("EMPLOYE SALARY :"+microSoft2.salary);
System.out.println("EMPLOYE STATUS :"+microSoft2.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft2.gender);
System.out.println("EMPLOYE LOCATION :"+microSoft2.location);
System.out.println("EMPLOYE JOIN DATE :"+microSoft2.joining_date);
System.out.println("EMPLOYE NAME :"+microSoft2.employe_name1);
System.out.println("EMPLOYE AGE :"+microSoft2.age1);
System.out.println("EMPLOYE ID NUMBER :"+microSoft2.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft2.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft2.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft2.experience1);
System.out.println("EMPLOYE SALARY :"+microSoft2.salary1);
System.out.println("EMPLOYE STATUS :"+microSoft2.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft2.gender1);
System.out.println("EMPLOYE LOCATION :"+microSoft2.location1);
System.out.println("EMPLOYE JOIN DATE :"+microSoft2.joining_date1);

MicroSoft microSoft3 = new MicroSoft();
System.out.println("EMPLOYE NAME :"+microSoft3.employe_name);
System.out.println("EMPLOYE AGE :"+microSoft3.age);
System.out.println("EMPLOYE ID NUMBER :"+microSoft3.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft3.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft3.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft3.experience);
System.out.println("EMPLOYE SALARY :"+microSoft3.salary);
System.out.println("EMPLOYE STATUS :"+microSoft3.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft3.gender);
System.out.println("EMPLOYE LOCATION :"+microSoft3.location);
System.out.println("EMPLOYE JOIN DATE :"+microSoft3.joining_date);
System.out.println("EMPLOYE NAME :"+microSoft3.employe_name1);
System.out.println("EMPLOYE AGE :"+microSoft3.age1);
System.out.println("EMPLOYE ID NUMBER :"+microSoft3.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+microSoft3.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+microSoft3.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+microSoft3.experience1);
System.out.println("EMPLOYE SALARY :"+microSoft3.salary1);
System.out.println("EMPLOYE STATUS :"+microSoft3.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+microSoft3.gender1);
System.out.println("EMPLOYE LOCATION :"+microSoft3.location1);
System.out.println("EMPLOYE JOIN DATE :"+microSoft3.joining_date1);

new MicroSoft();
}
}