public class WiproRunner{
public static void main(String[] args){
Wipro wipro = new Wipro();
System.out.println("EMPLOYE NAME :"+wipro.employe_name);
System.out.println("EMPLOYE AGE :"+wipro.age);
System.out.println("EMPLOYE ID NUMBER :"+wipro.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+wipro.experience);
System.out.println("EMPLOYE SALARY :"+wipro.salary);
System.out.println("EMPLOYE STATUS :"+wipro.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro.gender);
System.out.println("EMPLOYE LOCATION :"+wipro.location);
System.out.println("EMPLOYE JOIN DATE :"+wipro.joining_date);
System.out.println("EMPLOYE NAME :"+wipro.employe_name1);
System.out.println("EMPLOYE AGE :"+wipro.age1);
System.out.println("EMPLOYE ID NUMBER :"+wipro.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+wipro.experience1);
System.out.println("EMPLOYE SALARY :"+wipro.salary1);
System.out.println("EMPLOYE STATUS :"+wipro.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro.gender1);
System.out.println("EMPLOYE LOCATION :"+wipro.location1);
System.out.println("EMPLOYE JOIN DATE :"+wipro.joining_date1);

Wipro wipro1 = new Wipro();
System.out.println("EMPLOYE NAME :"+wipro1.employe_name);
System.out.println("EMPLOYE AGE :"+wipro1.age);
System.out.println("EMPLOYE ID NUMBER :"+wipro1.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro1.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro1.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+wipro1.experience);
System.out.println("EMPLOYE SALARY :"+wipro1.salary);
System.out.println("EMPLOYE STATUS :"+wipro1.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro1.gender);
System.out.println("EMPLOYE LOCATION :"+wipro1.location);
System.out.println("EMPLOYE JOIN DATE :"+wipro1.joining_date);
System.out.println("EMPLOYE NAME :"+wipro1.employe_name1);
System.out.println("EMPLOYE AGE :"+wipro1.age1);
System.out.println("EMPLOYE ID NUMBER :"+wipro1.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro1.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro1.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+wipro1.experience1);
System.out.println("EMPLOYE SALARY :"+wipro1.salary1);
System.out.println("EMPLOYE STATUS :"+wipro1.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro1.gender1);
System.out.println("EMPLOYE LOCATION :"+wipro1.location1);
System.out.println("EMPLOYE JOIN DATE :"+wipro1.joining_date1);

Wipro wipro2 = new Wipro();
System.out.println("EMPLOYE NAME :"+wipro2.employe_name);
System.out.println("EMPLOYE AGE :"+wipro2.age);
System.out.println("EMPLOYE ID NUMBER :"+wipro2.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro2.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro2.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+wipro2.experience);
System.out.println("EMPLOYE SALARY :"+wipro2.salary);
System.out.println("EMPLOYE STATUS :"+wipro2.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro2.gender);
System.out.println("EMPLOYE LOCATION :"+wipro2.location);
System.out.println("EMPLOYE JOIN DATE :"+wipro2.joining_date);
System.out.println("EMPLOYE NAME :"+wipro2.employe_name1);
System.out.println("EMPLOYE AGE :"+wipro2.age1);
System.out.println("EMPLOYE ID NUMBER :"+wipro2.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro2.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro2.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+wipro2.experience1);
System.out.println("EMPLOYE SALARY :"+wipro2.salary1);
System.out.println("EMPLOYE STATUS :"+wipro2.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro2.gender1);
System.out.println("EMPLOYE LOCATION :"+wipro2.location1);
System.out.println("EMPLOYE JOIN DATE :"+wipro2.joining_date1);

Wipro wipro3 = new Wipro();
System.out.println("EMPLOYE NAME :"+wipro3.employe_name);
System.out.println("EMPLOYE AGE :"+wipro3.age);
System.out.println("EMPLOYE ID NUMBER :"+wipro3.id_number);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro3.nuber_of_holidays);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro3.phone_number);
System.out.println("EMPLOYE EXPERIENCE :"+wipro3.experience);
System.out.println("EMPLOYE SALARY :"+wipro3.salary);
System.out.println("EMPLOYE STATUS :"+wipro3.isAvtive);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro3.gender);
System.out.println("EMPLOYE LOCATION :"+wipro3.location);
System.out.println("EMPLOYE JOIN DATE :"+wipro3.joining_date);
System.out.println("EMPLOYE NAME :"+wipro3.employe_name1);
System.out.println("EMPLOYE AGE :"+wipro3.age1);
System.out.println("EMPLOYE ID NUMBER :"+wipro3.id_number1);
System.out.println("EMPLOYE TOTAL HOLIDAY/YEAR :"+wipro3.nuber_of_holidays1);
System.out.println("EMPLOYE PHONE NUMBER :"+wipro3.phone_number1);
System.out.println("EMPLOYE EXPERIENCE :"+wipro3.experience1);
System.out.println("EMPLOYE SALARY :"+wipro3.salary1);
System.out.println("EMPLOYE STATUS :"+wipro3.isAvtive1);
System.out.println("EMPLOYE GENDER MALE(M)/FEMALE(F) :"+wipro3.gender1);
System.out.println("EMPLOYE LOCATION :"+wipro3.location1);
System.out.println("EMPLOYE JOIN DATE :"+wipro3.joining_date1);

new Wipro();
}
}